const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
history.scrollRestoration="manual";
addEventListener("load",()=>scrollTo({top:0,left:0,behavior:"instant"}));
const canvas=$("#lake"),ctx=canvas.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2);let w,h,mouse={x:innerWidth*.65,y:innerHeight*.55,on:false},ripples=[],stars=[],lastRipple=0;
function resize(){w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(100,Math.floor(w/12))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.3,a:Math.random()*.35+.08,s:Math.random()*.16+.03,p:Math.random()*6.28}))}
function ripple(x,y,power=1){ripples.push({x,y,r:4,a:Math.min(.95,.72*power),s:2.1+power,seed:Math.random()*6.28});if(ripples.length>12)ripples.shift()}
function drawDragonfly(t){
  const baseX=mouse.on?Math.max(45,Math.min(mouse.x,w-45)):w*.72,baseY=mouse.on?Math.max(70,Math.min(mouse.y,h-55)):h*.37,x=baseX+Math.sin(t*.0017)*14,y=baseY-34+Math.cos(t*.0023)*6,angle=Math.sin(t*.0012)*.13;
  ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowBlur=17;ctx.shadowColor="rgba(147,238,218,.7)";
  for(const side of [-1,1])for(const back of [-1,1]){ctx.save();ctx.scale(side,1);ctx.rotate(back*.2+Math.sin(t*.018+back)*.08);ctx.beginPath();ctx.ellipse(16,back*5,19,5.5,back*.28,0,6.28);ctx.fillStyle="rgba(183,239,225,.24)";ctx.fill();ctx.strokeStyle="rgba(194,246,232,.7)";ctx.lineWidth=.7;ctx.stroke();ctx.restore()}
  ctx.shadowBlur=10;ctx.beginPath();ctx.ellipse(0,0,4,12,0,0,6.28);ctx.fillStyle="#79c9b9";ctx.fill();ctx.beginPath();ctx.arc(0,-10,4.5,0,6.28);ctx.fillStyle="#d8b96d";ctx.fill();ctx.beginPath();ctx.moveTo(0,9);ctx.lineTo(0,27);ctx.strokeStyle="#79c9b9";ctx.lineWidth=2;ctx.stroke();ctx.restore();
  ctx.save();ctx.beginPath();ctx.ellipse(x,y+37,30,5,0,0,6.28);ctx.fillStyle="rgba(130,220,202,.08)";ctx.fill();ctx.restore();
}
function draw(t){ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w*.69,h*.28,0,w*.69,h*.28,w*.7);g.addColorStop(0,"rgba(86,147,135,.25)");g.addColorStop(.35,"rgba(14,64,69,.14)");g.addColorStop(1,"rgba(1,7,13,.12)");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);stars.forEach(p=>{p.y-=p.s;if(p.y<0){p.y=h;p.x=Math.random()*w}ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,6.28);ctx.fillStyle=`rgba(195,232,220,${p.a*(.65+Math.sin(t*.001+p.p)*.35)})`;ctx.fill()});const line=h*.58;ctx.save();ctx.beginPath();ctx.rect(0,line,w,h-line);ctx.clip();for(let i=0;i<20;i++){let y=line+i*14+Math.sin(t*.0007+i)*4;ctx.beginPath();for(let x=-20;x<w+20;x+=16){let n=mouse.on?Math.max(0,1-Math.hypot(x-mouse.x,y-mouse.y)/230):0,v=Math.sin(x*.018+t*.0012+i*.7)*(1.4+n*9);x===-20?ctx.moveTo(x,y+v):ctx.lineTo(x,y+v)}ctx.strokeStyle=`rgba(145,211,199,${.045+i*.0018})`;ctx.stroke()}ctx.restore();ripples=ripples.filter(r=>r.a>.018);ripples.forEach(r=>{ctx.save();ctx.shadowBlur=14;ctx.shadowColor=`rgba(133,241,217,${r.a})`;for(let ring=0;ring<3;ring++){const radius=Math.max(1,r.r-ring*13);ctx.beginPath();ctx.ellipse(r.x,r.y,radius*1.9,radius*.52,0,0,6.28);ctx.strokeStyle=`rgba(171,245,226,${r.a*(1-ring*.24)})`;ctx.lineWidth=Math.max(.8,2.4-ring*.55);ctx.stroke()}for(let i=0;i<18;i++){const a=i/18*6.28+r.seed,px=r.x+Math.cos(a)*r.r*1.9,py=r.y+Math.sin(a)*r.r*.52;ctx.beginPath();ctx.arc(px,py,1.1+Math.sin(t*.01+i)*.55,0,6.28);ctx.fillStyle=`rgba(203,255,240,${r.a*.9})`;ctx.fill()}ctx.restore();r.r+=r.s;r.a*=.958});drawDragonfly(t);requestAnimationFrame(draw)}
resize();requestAnimationFrame(draw);addEventListener("resize",resize);addEventListener("pointermove",e=>{mouse={x:e.clientX,y:e.clientY,on:true};const now=performance.now();if(now-lastRipple>115){ripple(e.clientX,e.clientY,.52);lastRipple=now}});addEventListener("pointerleave",()=>mouse.on=false);addEventListener("pointerdown",e=>{ripple(e.clientX,e.clientY,1.35);sparks(e.clientX,e.clientY,14)});addEventListener("touchmove",e=>{const p=e.touches[0];if(p){mouse={x:p.clientX,y:p.clientY,on:true};const now=performance.now();if(now-lastRipple>140){ripple(p.clientX,p.clientY,.65);lastRipple=now}}},{passive:true});

const pad=n=>String(n).padStart(2,"0");let guessed=null;function period(n){return n<5?"深夜":n<9?"清晨":n<12?"上午":n<14?"正午":n<18?"午后":n<23?"夜晚":"深夜"}setInterval(()=>{if(!guessed)$("#statusText").textContent="正在感知此刻"+".".repeat(new Date().getSeconds()%3+1)},1000);
$("#revealButton").addEventListener("click",()=>{const button=$("#revealButton"),text=button.querySelector("span");button.disabled=true;let n=0;const timer=setInterval(()=>{let d=new Date(Date.now()+(Math.random()*20-10)*60000);text.textContent=`${pad(d.getHours())} : ${pad(d.getMinutes())}`;if(++n>9){clearInterval(timer);guessed=new Date(Date.now()+(Math.floor(Math.random()*11)-5)*60000);$("#guessDate").textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(guessed);$("#guessTime").textContent=`${pad(guessed.getHours())}:${pad(guessed.getMinutes())}`;$("#periodText").textContent=period(guessed.getHours());button.style.display="none";$("#prediction").classList.add("visible");$("#prediction").setAttribute("aria-hidden","false");$("#statusText").textContent="此刻已被看见";ripple(w*.5,h*.62,1.8)}},90)});
$("#verifyButton").addEventListener("click",()=>{const d=Math.round(Math.abs(Date.now()-guessed)/60000);toast(d===0?"正好命中。看来今天的默契不错。":`只差 ${d} 分钟。雾很薄，我们离得很近。`)});

const deckPages=$$(".deck-page"),dots=$$(".page-dot"),siteDeck=$("#siteDeck");let deckIndex=0,wheelLock=false,touchStartY=0;
function showDeckPage(id,scrollToDeck=true){
  const nextIndex=deckPages.findIndex(page=>page.dataset.pageName===id);if(nextIndex<0)return;
  const previous=deckPages[deckIndex];previous.classList.toggle("exit-up",nextIndex>deckIndex);previous.classList.remove("active");previous.setAttribute("aria-hidden","true");
  deckIndex=nextIndex;const current=deckPages[deckIndex];current.classList.remove("exit-up");current.classList.add("active");current.setAttribute("aria-hidden","false");
  dots.forEach(dot=>{const active=dot.dataset.page===id;dot.classList.toggle("active",active);active?dot.setAttribute("aria-current","page"):dot.removeAttribute("aria-current")});
  if(scrollToDeck)siteDeck.scrollIntoView({behavior:"smooth",block:"start"});
}
function go(id){if(id==="cover"){$("#cover").scrollIntoView({behavior:"smooth",block:"start"});return}showDeckPage(id,true)}
$$('[data-next]').forEach(button=>button.addEventListener("click",()=>go(button.dataset.next)));dots.forEach(button=>button.addEventListener("click",()=>go(button.dataset.page)));$(".logo").addEventListener("click",()=>go("cover"));
new IntersectionObserver(entries=>entries.forEach(entry=>document.body.classList.toggle("cover-active",entry.isIntersecting&&entry.intersectionRatio>.55)),{threshold:[.55]}).observe($("#cover"));
function stepDeck(step){const next=deckIndex+step;if(next<0){go("cover");return}if(next>=deckPages.length)return;showDeckPage(deckPages[next].dataset.pageName,true)}
addEventListener("wheel",event=>{if(wheelLock||Math.abs(event.deltaY)<18||event.target.closest(".music-drawer"))return;event.preventDefault();wheelLock=true;if(document.body.classList.contains("cover-active")){if(event.deltaY>0)showDeckPage("home",true)}else stepDeck(event.deltaY>0?1:-1);setTimeout(()=>wheelLock=false,720)},{passive:false});
addEventListener("touchstart",event=>{touchStartY=event.touches[0]?.clientY||0},{passive:true});
addEventListener("touchend",event=>{const endY=event.changedTouches[0]?.clientY||touchStartY,delta=touchStartY-endY;if(Math.abs(delta)<48)return;if(document.body.classList.contains("cover-active")){if(delta>0)showDeckPage("home",true)}else stepDeck(delta>0?1:-1)},{passive:true});
let notebookPointerY=0;const coverNotebook=$("#coverNotebook");coverNotebook.addEventListener("pointerdown",event=>notebookPointerY=event.clientY);coverNotebook.addEventListener("pointerup",event=>{if(Math.abs(event.clientY-notebookPointerY)>24)showDeckPage("home",true)});

const productCards=$$("[data-product]"),productTabs=$$("[data-product-go]");let currentProduct=0,productLocked=false;function showProduct(index,direction=1){if(productLocked||index===currentProduct)return;productLocked=true;const old=productCards[currentProduct];index=(index+productCards.length)%productCards.length;old.classList.add("turn-out");setTimeout(()=>{old.classList.remove("active","turn-out");old.setAttribute("aria-hidden","true");currentProduct=index;const next=productCards[currentProduct];next.classList.add("active");next.removeAttribute("aria-hidden");productTabs.forEach((b,i)=>b.classList.toggle("active",i===currentProduct));productLocked=false},330)}$(".next-product").addEventListener("click",()=>showProduct((currentProduct+1)%productCards.length,1));$(".prev-product").addEventListener("click",()=>showProduct((currentProduct-1+productCards.length)%productCards.length,-1));productTabs.forEach((b,i)=>b.addEventListener("click",()=>showProduct(i,i>currentProduct?1:-1)));
$$('[data-variant]').forEach(button=>button.addEventListener("click",()=>{const group=button.closest(".variant-list");group.querySelectorAll("button").forEach(item=>item.classList.toggle("active",item===button));toast(`已选中：${button.dataset.variant}`);const rect=button.getBoundingClientRect();sparks(rect.left+rect.width/2,rect.top,7)}));

const copyBank={
  "钢笔":["钢笔把普通的一天写成值得珍藏的一页——握住它，也握住你想认真对待的每一个答案。","好的钢笔不会催你快一点，它只会让每一次落笔，都更像你自己。"],
  "铅笔":["铅笔允许你修改，也提醒你：成长从来不是一次写对，而是愿意再试一次。","留一点可以擦去的余地，也给每个还没确定的梦想，一次被认真写下的机会。"],
  "书本":["一本好书像一扇随身携带的门，翻开它，今天的书桌就能通向更远的地方。","买下的不只是纸页，而是未来某天，你会感谢自己读过的那些时刻。"],
  "图书":["图书不会替你决定答案，却会悄悄扩大你能选择的世界。","让一本想读很久的书来到身边，也许下一次心动，就藏在翻页声里。"],
  "文具盒":["把零散的笔和灵感都收好——桌面清爽一点，想开始的心情也会更近一点。","一个真正懂你的文具盒，装得下常用的笔，也装得下随时出发的认真。"]
};
const wordInput=$("#stationeryWord"),copyResult=$("#copyResult"),generatedCopy=$("#generatedCopy");function generateCopy(raw){const word=raw.trim().slice(0,12);if(!word){toast("先写下一种你喜欢的文具吧。");wordInput.focus();return}const key=Object.keys(copyBank).find(k=>word.includes(k));const list=key?copyBank[key]:[`也许「${word}」吸引你的，不只是它的样子，而是它能让平凡的学习时刻，变得更像一件值得期待的小事。`,`把「${word}」留在手边，不是为了拥有更多，而是为了让每一次想认真开始时，都刚好有喜欢的东西陪着你。`];generatedCopy.textContent=`“${list[Math.floor(Math.random()*list.length)]}”`;copyResult.classList.remove("flash");void copyResult.offsetWidth;copyResult.classList.add("flash");ripple(innerWidth*.75,innerHeight*.54,1.3);sparks(innerWidth*.75,innerHeight*.54,12)}$("#wordForm").addEventListener("submit",e=>{e.preventDefault();generateCopy(wordInput.value)});$$('[data-word]').forEach(b=>b.addEventListener("click",()=>{wordInput.value=b.dataset.word;generateCopy(b.dataset.word)}));$("#randomCopy").addEventListener("click",()=>{const keys=Object.keys(copyBank),word=keys[Math.floor(Math.random()*keys.length)];wordInput.value=word;generateCopy(word)});
$$('.heart').forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("liked");b.textContent=b.classList.contains("liked")?"♥":"♡";toast(b.classList.contains("liked")?"已放进你的心愿清单。":"已从心愿清单移除。")}));$$('.tab').forEach(b=>b.addEventListener("click",()=>{$$('.tab').forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-selected",String(x===b))});$$('.panel').forEach(p=>{const on=p.dataset.panel===b.dataset.tab;p.hidden=!on;p.classList.toggle("active",on)})}));$("#copyAddress").addEventListener("click",async()=>{try{await navigator.clipboard.writeText("中国某某省某某市创意街区88号，片刻文具局售后部，邮编000000");toast("地址已复制。记得换成真实信息。")}catch{toast("复制失败，请手动选择地址文字。")}});
let toastTimer;function toast(s){clearTimeout(toastTimer);$("#toast").textContent=s;$("#toast").classList.add("show");toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),3200)}function sparks(x,y,n=8){for(let i=0;i<n;i++){const s=document.createElement("i");s.className="spark";s.style.left=x+"px";s.style.top=y+"px";const a=Math.random()*6.28,d=25+Math.random()*70;s.style.setProperty("--tx",Math.cos(a)*d+"px");s.style.setProperty("--ty",Math.sin(a)*d+"px");document.body.appendChild(s);setTimeout(()=>s.remove(),950)}}

const musicButton=$("#musicButton"),drawer=$("#musicDrawer"),playButton=$("#playTrack"),audio=new Audio();let ac,nodes=[],ambientTimer,tracks=[],trackIndex=0,playing=false;function tone(f,delay,duration){const o=ac.createOscillator(),g=ac.createGain();o.type="sine";o.frequency.value=f;g.gain.setValueAtTime(0,ac.currentTime+delay);g.gain.linearRampToValueAtTime(.035,ac.currentTime+delay+1.1);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+delay+duration);o.connect(g).connect(ac.destination);o.start(ac.currentTime+delay);o.stop(ac.currentTime+delay+duration+.1);nodes.push(o)}function ambient(){if(!playing||tracks.length)return;const root=[196,220,246.94][Math.floor(Math.random()*3)];tone(root,0,5.8);tone(root*1.5,.7,4.6);ambientTimer=setTimeout(ambient,4600)}async function setPlaying(on){playing=on;musicButton.setAttribute("aria-pressed",String(on));musicButton.querySelector("span").textContent=on?"声音流动中":"唤醒声音";playButton.textContent=on?"Ⅱ":"▶";if(on){if(tracks.length)await audio.play();else{ac||=new(window.AudioContext||window.webkitAudioContext)();await ac.resume();clearTimeout(ambientTimer);ambient()}}else{audio.pause();clearTimeout(ambientTimer);nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[]}}
musicButton.addEventListener("click",()=>{drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");if(!playing)setPlaying(true).catch(()=>toast("浏览器暂时没有允许播放声音。"))});$("#drawerClose").addEventListener("click",()=>{drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true")});playButton.addEventListener("click",()=>setPlaying(!playing));function loadTrack(i){if(!tracks.length)return;trackIndex=(i+tracks.length)%tracks.length;audio.src=tracks[trackIndex].url;$("#trackName").textContent=tracks[trackIndex].name;$("#trackMeta").textContent=`${trackIndex+1} / ${tracks.length} · 你的本地歌单`;if(playing)audio.play()}$("#musicFiles").addEventListener("change",e=>{tracks.forEach(t=>URL.revokeObjectURL(t.url));tracks=[...e.target.files].map(f=>({name:f.name.replace(/\.[^.]+$/,""),url:URL.createObjectURL(f)})).sort(()=>Math.random()-.5);if(!tracks.length)return;clearTimeout(ambientTimer);nodes.forEach(n=>{try{n.stop()}catch{}});loadTrack(0);setPlaying(true);toast(`已随机打乱 ${tracks.length} 首音乐。`)});$("#prevTrack").addEventListener("click",()=>loadTrack(trackIndex-1));$("#nextTrack").addEventListener("click",()=>loadTrack(trackIndex+1));audio.addEventListener("ended",()=>loadTrack(trackIndex+1));$("#year").textContent=new Date().getFullYear();
